### ISSUE TITLE
Problem with sending notifications/reminders

### ISSUE THREAD

**Issue by tammo293** [lsuonline/lsuce-block_quickmail#17]
Hi,

the plugin is great and works very well! However, I have a small problem with the notifications.
I have set a reminder in a course, I want this reminder to be sent to all users who have not reached 80% (or more) of the score or who have never done the course (according to the course and activity completion criteria).
I have therefore set the reminder to be sent every 2 days to all users who have a rating between 0 and 79. The problem is that when I look in the last run it shows that the email has been sent, but none of the users who meet either of the above conditions have received the email.
I'm using moodle 3.10.4 and sending the emails works fine (in fact if I send a normal Course Message instead of a notification, the email reaches the users correctly).

Thank you in advance and thanks again for the great plugin!

**Comment by tammo293** [comment]
An update.
The notification email arrives correctly to those who have done the course with a score between 0 and 80. The email does NOT arrive correctly to those who have not yet taken the course.

**Comment by rrusso** [comment]
I believe this should be done with a notification and a reminder.

The notification is based off events which are not fired when someone does not have a grade or has not done anything in the course.

Reminders are based on timing, so I would set a reminder for people who have not accessed the course yet and then set the notification for the grade criteria you want.
