### ISSUE TITLE
Debug notifications

### ISSUE THREAD

**Issue by hdagheda** [lsuonline/lsuce-block_quickmail#24]
With Debug on, it shows these debug messages before redirecting -  when updating/saving signatures; alternate emails; editing drafts, back button click etc

`
You should really redirect before you start page output

    line 1243 of /lib/outputrenderers.php: call to debugging()

    line 2970 of /lib/weblib.php: call to core_renderer->redirect_message()

    line 155 of /blocks/quickmail/classes/controllers/support/controller_request.php: call to redirect()

    line 162 of /blocks/quickmail/classes/controllers/support/controller_request.php: call to block_quickmail\controllers\support\controller_request->redirect_as_type()

    line 152 of /blocks/quickmail/classes/controllers/queued_message_index_controller.php: call to block_quickmail\controllers\support\controller_request->redirect_as_success()

    line ? of unknownfile: call to block_quickmail\controllers\queued_message_index_controller->action_send()

    line 144 of /blocks/quickmail/classes/controllers/support/base_controller.php: call to call_user_func()

    line 83 of /blocks/quickmail/classes/controllers/support/base_controller.php: call to block_quickmail\controllers\support\base_controller->call_action()

    line 72 of /blocks/quickmail/queued.php: call to block_quickmail\controllers\support\base_controller::handle()`

**Comment by ChaoticDalo** [comment]
PR complete, thank you.
