### ISSUE TITLE
Attachments are not saved for drafts

### ISSUE THREAD

**Issue by rlorenzo** [lsuonline/lsuce-block_quickmail#4]
We are using the plugin version 2019012401.

When we attached the file, saved the draft, left the Quickmail block, and returned to the draft, the message was saved, but the attachment was missing.

This was working on the older version of the plugin version 2017122001.

**Comment by rrusso** [comment]
Steven is looking at this.

**Comment by amandadoughty** [comment]
We also have this problem. v2021030200 on Moodle v3.9.11
