### ISSUE TITLE
Moodle 4.0 support?

### ISSUE THREAD

**Issue by durzo** [lsuonline/lsuce-block_quickmail#58]
Does this plugin support Moodle 4.0 ?

**Comment by tafkey** [comment]
+1

**Comment by LMachucaORT** [comment]
+1

**Comment by nisaDoc** [comment]
Hello,

we have done with testing. We have just small notices for possible bugs, which also occur in V3.11:
- it does not support format_string
- After re-sending an email from the site /alternate.php?courseid=xx, we get to alternate.php?courseid=0. I do not know why the courseid equal to 0. It should be acctually the course id, where we have been before.
- After re-sending an email, we come to dashboard with the button "back to my page" back. I would expect, that we get back to the course site, where we have resent that mail.
- and the breadcrum in the site alternate.php was gone after resending an email.

overall with those small notices, the plugin works on moodle v4.x.
I hope, this info can help you.

Best regards,
Nisa

**Comment by Tottebee** [comment]
Hi there,
are you still working on upgrading the block for Moodle 4.1? We are hosting moodle for schools in germany and the quickmail block ist a "wanted one" : ) 
If you don't have the capacaty to fix the bugs - is it possible, that I could hire an developer, let him fix the issues and give the code back to you? That`s because I don't want to create a fork of the plugin and also speed up the availability of this plugin for the community. Or is there another way to make this happen ?
regards
Thorsten

**Comment by nisaDoc** [comment]
hi Thorsten,
if you're asking me to fix those bugs, I am not developer of this plugin. Yes you can hire any developer. But, I dont think the developer of this plugin is active developing.
Without fixing those bugs, this plugin is still useable. There are jus small bugs, that dont risk the functionality of this plugin.

regards,
Nisa

**Comment by Tottebee** [comment]
Thanks Nisa,
my question was pointing to the maintainers of this plugin : ) 
What i don't know is, if its possible to replace the original plugin in the moodle database with a newer one, if you are not the original developer... If not - two almost similar blocks does not makes sense imho.

**Comment by SLOC100** [comment]
Just wondering if there will there be support for the Quickmail plugin for Moodle version 4.0 ? Our instructors really liked using this block over Moodle messaging. Just wondering :)

**Comment by moodleadmin72** [comment]
Yes, I would like to know as well. This was a useful tool for our instructors as well and would love to have it available in our new site. Does anyone have any updates about the plugin for Moodle 4.0 or 4.1?

**Comment by ChaoticDalo** [comment]
Plugin update on July 28th resolves this.
