### ISSUE TITLE
Module is broken in Moodle 4.2

### ISSUE THREAD

**Issue by der-martin85** [lsuonline/lsuce-block_quickmail#63]
The block does not appear in courses. Installation showed no problems. I'm using php 8.1 and Moodle 4.2+ (20230504).

**Comment by Syxton** [comment]
@der-martin85 You should rebase your changes to the current master and only include 4.2 compatibility fixes.

**Comment by der-martin85** [comment]
I made a new pull request #65

**Comment by ChaoticDalo** [comment]
Fix has been merged into master and release/MOODLE_421_STABLE
