### ISSUE TITLE
Cannot compose course messages 

### ISSUE THREAD

**Issue by markazalsunnah** [lsuonline/lsuce-block_quickmail#70]
Hi
I cannot compose course messages, when trying to create a new course message I run into this error
![image](https://github.com/lsuonline/lsuce-block_quickmail/assets/139154415/70835ca9-4ddc-4fc1-8c2c-fb85c10a338b)

Exception - Call to undefined function file_get_submitted_draft_itemid()

- I am using Moodle 4.2
- My Moodle is deployed to Kubernetes via the bitnami helm chart
- I only installed quickmail today via the zip file from Moodle's plugin directory

**Comment by ChaoticDalo** [comment]
Fixed
