### ISSUE TITLE
Cannot duplicate a message in quickmail

### ISSUE THREAD

**Issue by sestrauss** [lsuonline/lsuce-block_quickmail#74]
Thanks for taking over the QM project. I don't know what I would do without this tool!!!

I found a small bug, which was first reported by a colleague of mine using a different Moodle instance at a different school. I don't know much about her instance, but I have Quickmail v4.2.1
2023070700
On Moodle 4.1.5 (build 20230818)

The bug is very easily and consistently replicated on my system.

When I hit the "Duplicate" button, I get the error:

"Exception - block_quickmail\filemanager\message_file_handler::__construct(): Argument #1 ($message) must be of type block_quickmail\persistents\message, null given, called in [dirroot]/blocks/quickmail/classes/filemanager/message_file_handler.php on line 79"

**Comment by Syxton** [comment]
#83 will fix this.  I used the wrong variable name in the message duplication.  It was different than the draft duplication area.
