### ISSUE TITLE
Localization / Custom languages

### ISSUE THREAD

**Issue by ElectricCircus** [lsuonline/lsuce-block_quickmail#85]
Some user interface strings are hard coded in english, so they cannot be translated/localizated to others.

Examples:
My Signatures->Select Signature To Edit: "**Create New**"
Compose Course Message->To: "**student** (**Role**)", "History 2 (**Group**)"

**Comment by ChaoticDalo** [comment]
I have updated the ones you pointed out and will be pushing code soon.
Are there others?
