### ISSUE TITLE
Creating new alternate email after deleting one - exception thrown

### ISSUE THREAD

**Issue by kkrzyzaniak** [lsuonline/lsuce-block_quickmail#86]
Steps to reproduce:
1. Create one alternate email address eg. “Only me, in any course” , confirm it.
2. Create another one eg. selecting Roles, save it.
3. Delete alternate email address from step two.
4. Try to add new alternate email address by clicking 'add new' in Alternate emails then error occurs- see image attached.

It looks like problem with redirection after delete action.

![Screenshot from 2024-06-10 18-12-24](https://github.com/lsuonline/lsuce-block_quickmail/assets/150013724/83c1f212-7146-4fa6-963b-079a8621cd35)

**Comment by ChaoticDalo** [comment]
Fixed.
